// Compendium content, generated by tools/build-content.mjs:
//   content/<lang>/index.json       every section and item, with time badges and a short lead
//   content/<lang>/<section>.json   one full section, loaded on demand
import { lang } from './i18n.js';

const cache = new Map();

function load(path) {
  if (!cache.has(path)) {
    cache.set(path, fetch(new URL(`../../content/${path}`, import.meta.url))
      .then((r) => { if (!r.ok) throw new Error(`content ${path}: ${r.status}`); return r.json(); })
      .catch((e) => { cache.delete(path); throw e; }));
  }
  return cache.get(path);
}

export const index = (code = lang()) => load(`${code}/index.json`);

export async function section(id, code = lang()) {
  const idx = await index(code);
  if (!idx.sections.some((s) => s.id === id)) return null;
  return load(`${code}/${id}.json`);
}

export async function item(id, code = lang()) {
  const idx = await index(code);
  const s = idx.sections.find((x) => x.items.some((i) => i.id === id));
  if (!s) return null;
  const full = await section(s.id, code);
  return { item: full.items.find((i) => i.id === id), section: full };
}
